// src/components/Layout/MainLayout.tsx
import React, { useState } from 'react';
import Sidebar from './Sidebar';
import Header from './Header';
interface MainLayoutProps {
  children: React.ReactNode;
}
const MainLayout: React.FC<MainLayoutProps> = ({
  children
}) => {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  return <div className="flex h-screen bg-gray-100">
      <Sidebar isOpen={sidebarOpen} setIsOpen={setSidebarOpen} />
      <div className="flex flex-col flex-1 overflow-hidden">
        <Header onMenuClick={() => setSidebarOpen(true)} />
        <main className="flex-1 overflow-y-auto p-4 md:p-6">{children}</main>
      </div>
    </div>;
};
export default MainLayout;

// front/src/components/layout/MainLayout.vue
<template>
  <div class="flex h-screen bg-gray-100">
    <AppSidebar :isOpen="sidebarOpen" @close="sidebarOpen = false" />
    <div class="flex flex-col flex-1 overflow-hidden">
      <AppHeader :onMenuClick="() => (sidebarOpen = true)" />
      <main class="flex-1 overflow-y-auto md:p-6 ml-64">
        <RouterView />
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { RouterView } from "vue-router";
import AppSidebar from "./Sidebar.vue";
import AppHeader from "./Header.vue";

const sidebarOpen = ref(false);
</script>
